import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import css from './KanyeCard.module.css';
/** One numeric field row with a reset control. */
function NumberField({ id, label, hint, value, disabled, onEdit, onReset, t, }) {
    return (_jsxs("div", { className: css.fieldRow, children: [_jsxs("label", { className: css.fieldLabel, htmlFor: id, children: [_jsx("span", { className: css.rowTitle, children: label }), _jsx("span", { className: css.rowHint, children: hint })] }), _jsxs("div", { className: css.fieldControl, children: [_jsx("input", { id: id, className: css.fieldInput, type: "text", inputMode: "decimal", value: value.text, disabled: disabled, "aria-invalid": value.invalid, onChange: (event) => { onEdit(event.target.value); } }), _jsx("button", { type: "button", className: css.button, disabled: disabled, onClick: onReset, children: t('reset') })] }), value.invalid ? _jsx("span", { className: css.fieldError, children: t('invalidNumber') }) : null] }));
}
/** Render the kanye-pet card. */
export function KanyeCard(props) {
    const { t } = props;
    const state = props.useKanyeCard(snapshot => snapshot);
    const disabled = !state.writable;
    if (!state.available)
        return null;
    return (_jsxs("section", { className: css.section, children: [_jsxs("div", { className: css.heading, children: [_jsx("h3", { className: css.cardTitle, children: t('cardTitle') }), _jsx("p", { className: css.cardDescription, children: t('cardDescription') })] }), _jsxs("div", { className: css.row, children: [_jsxs("div", { className: css.rowLabel, children: [_jsx("span", { className: css.rowTitle, children: t('desktopPet') }), _jsx("span", { className: css.rowHint, children: t('desktopPetHint') })] }), _jsx("button", { type: "button", className: css.switch, "data-on": String(state.desktopPetEnabled), "aria-pressed": state.desktopPetEnabled, disabled: disabled, onClick: props.toggleDesktopPet })] }), _jsxs("div", { className: css.row, children: [_jsxs("div", { className: css.rowLabel, children: [_jsx("span", { className: css.rowTitle, children: t('character') }), _jsx("span", { className: css.rowHint, children: t('characterHint') })] }), _jsx("select", { className: css.fieldInput, value: state.character, disabled: disabled || !state.charactersLoaded || state.characters.length === 0, onChange: (event) => { props.edit('character', event.target.value); }, children: state.charactersLoaded && state.characters.length === 0
                            ? _jsx("option", { value: state.character, children: state.character })
                            : state.characters.map(ch => (_jsx("option", { value: ch.id, children: ch.name }, ch.id))) })] }), _jsx(NumberField, { id: "plugin-config-kanye-size", label: t('size'), hint: t('sizeHint'), value: state.size, disabled: disabled, onEdit: (text) => { props.edit('size', text); }, onReset: () => { props.edit('size', '150'); }, t: t }), _jsx(NumberField, { id: "plugin-config-kanye-opacity", label: t('opacity'), hint: t('opacityHint'), value: state.opacity, disabled: disabled, onEdit: (text) => { props.edit('opacity', text); }, onReset: () => { props.edit('opacity', '1'); }, t: t }), _jsxs("div", { className: css.actions, children: [_jsx("button", { type: "button", className: css.button, "data-tone": "primary", disabled: disabled || !state.dirty || state.invalid || state.saving, onClick: props.save, children: state.saving ? '...' : t('save') }), _jsx("button", { type: "button", className: css.button, disabled: disabled || (!state.dirty && !state.saving), onClick: props.discard, children: t('discard') })] })] }));
}
//# sourceMappingURL=KanyeCard.js.map